name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install protobuf-compiler -y
      - name: Build
        run: cargo build --verbose
      - name: Publish
        run: cargo publish --allow-dirty --token "${{ secrets.CARGO_KEY }}"
